name: telegram_keep_account_dart
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  galaxeus_lib: ^0.0.23
  path: ^1.8.2
  telegram_client: ^0.3.64
